export const STRING = {
  apiError: 'Không kết nối được với máy chủ',
  login: 'Đăng nhập',
  save: 'Lưu',
  confirm: 'Xác nhận',
  cancel: 'Hủy',
  username: 'Tên đăng nhập',
  yourEmail: 'Your email',
  password: 'Your password',
  rememberPwd: 'Ghi nhớ đăng nhập',
  expressTimeOut: 'Phiên đăng nhập hết hạn, vui lòng đăng nhập lại',
  picture: 'Hình ảnh',
  signUp: {
    signUp: 'Đăng ký',
    phoneNumber: 'Số điện thoại',
    fullName: 'Họ và tên',
  },
  popup: {
    notice: 'Thông báo',
    error: 'Lỗi',
    success: 'Thành công',
  },
  changePwd: {
    newPwd: 'Mật khẩu mới',
    inputNewPwd: 'Nhập vào mật khẩu mới',
    currentPwd: 'Mật khẩu cũ',
    inputCurrentPwd: 'Nhập vào mật khẩu cũ',
    confirmPwd: 'Xác nhận mật khẩu mới',
    changePwdFistTime: 'Đổi mật khẩu lần đầu',
    changePwd: 'Đổi mật khẩu',
    reLogin: 'Đổi mật khẩu thành công, vui lòng đăng nhập lại!',
    changePwdSucces:
      'Đổi mật khẩu thành công, bạn có muốn lưu lại mật khẩu mới?',
  },
  form: {
    plhTextInput: 'Nhập nội dung',
  },
  valid: {
    notBeBlank: 'không được bỏ trống',
    length: 'Tối thiểu 8 ký tự',
    nonSpecialChar: 'Không được chứa ký tự đặc biệt',
    specialChar: 'Phải chứa ký tự đặc biệt',
    uppercaseChar: 'Ít nhất 1 ký tự viết hoa',
    lowercaseChar: 'Ít nhất 1 ký tự viết thường',
    pwdNotMatch: 'Mật khẩu nhập lại không khớp',
    numberChar: 'Ít nhất 1 ký tự số',
    plsInputQuanti: 'Vui lòng nhập số lượng',
    invalidQuanti: 'Số lượng không hợp lệ',
    numberMustBeInt: 'Vui lòng nhập số nguyên',
    orderStatusInvalid: 'Trạng thái đơn hàng không hợp lệ',
  },
  permission: {
    default: 'Bạn không có quyền thực hiện chức năng này',
  },
};
